services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5482:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=uploads
    volumes:
      - ./docker:/docker-entrypoint-initdb.d