services:
  localstack:
    image: localstack/localstack:4
    container_name: localstack
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    environment:
      - SERVICES=s3,lambda,iam,logs
      - DEBUG=0
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PERSISTENCE=1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock' # LAMBDA_EXECUTOR=docker
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  localstack_data:
